### ISSUE TITLE
Reputation sometimes not displaying with error

### ISSUE THREAD

**Issue by 2ndHouse** [Phanx/Progress#1]
The display sometimes displays nothing but "Progress" when it should be displaying reputation at level 110. The problem happens in Broken Isle zones for sure, not sure about older content.  A UI reload does not fix the problem. UI reload can also cause the display problem when it was working fine. Hovering over the display when broken throws out this error...

1x integer overflow attempting to store -1.#IND
[C]: in function `format'
Progress\Progress-7.1.0.0.lua:277: in function <Progress\Progress.lua:245>
(tail call): ?
ChocolateBar\Chocolate.lua:207: in function <ChocolateBar\Chocolate.lua:186>

Locals:
(*temporary) = "%s / %s (%d%%)"
(*temporary) = "0"
(*temporary) = "0"
(*temporary) = -1.#IND

**Comment by Phanx** [comment]
What faction were you expecting to see in that situation? The problem appears to be that the faction is reporting either (a) zero as the max rep value or (b) the same number for min and max rep values. Next time you see this happen, please run the following command and report back with the chat frame output:

`/dump GetWatchedFactionInfo()`

**Comment by 2ndHouse** [comment]
This was a mistake on my part thinking Diplomancer was a part of this addon (they feel like one addon to me). Diplomancer was missing Armies of LegionFall reputation for the Broken Shore. I added it into Diplomancer myself recently. The error only seems to happen when Diplomancer was not detecting a rep/zone correctly. I'll go ahead and close this for now.
